
import QueryProvider from "@/providers/QueryProvider";
import "./globals.css";
import { Toaster } from "sonner";
import AIChatInterface from "@/components/ChatWidget/ChatWidget";

export const metadata = {
  title: "Naina AI",
  description: "Generated by KaalCoders Devlopers",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <QueryProvider>
          {children}
                <AIChatInterface />

          <Toaster richColors position="top-right" />

        </QueryProvider>
      </body>
    </html>
  );
}
