import QueryProvider from "@/providers/QueryProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "./globals.css";
import { Toaster } from "sonner";
import AIChatInterface from "@/components/ChatWidget/ChatWidget";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Naina AI",
  description: "Generated by KaalCoders Developers",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.variable} suppressHydrationWarning>
      <body className="font-sans bg-white text-gray-900">
        <ThemeProvider attribute="class" defaultTheme="light">
          <QueryProvider>
            {children}
            {/* <AIChatInterface /> */}
            <Toaster richColors position="top-right" />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
