export const clients = [
  [
    {
      _id: "clt_001",
      companyName: "Kashitrip",
      contactPerson: "Vicky Bisht",
      email: "admin@kashitrip.com",
      phone: "+91-9876543210",
      plan: {
        type: "Pro",
        chatLimit: 10000,
        expiryDate: "2025-12-31T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: true,
        customPrompt: "Act as a travel expert for Varanasi.",
      },
      branding: {
        primaryColor: "#2563eb",
        secondaryColor: "#facc15",
      },
      analytics: {
        totalChats: 5423,
        activeUsers: 231,
        avgResponseTime: "2.4s",
      },
      status: "active",
    },
    {
      _id: "clt_002",
      companyName: "TechNova Systems",
      contactPerson: "Amit Patel",
      email: "amit@technova.io",
      phone: "+91-9812345678",
      plan: {
        type: "Enterprise",
        chatLimit: 50000,
        expiryDate: "2026-03-15T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o",
        memoryEnabled: true,
        customPrompt: "Provide technical support for IT clients.",
      },
      branding: {
        primaryColor: "#0ea5e9",
        secondaryColor: "#9333ea",
      },
      analytics: {
        totalChats: 12234,
        activeUsers: 508,
        avgResponseTime: "1.9s",
      },
      status: "active",
    },
    {
      _id: "clt_003",
      companyName: "EduSpark Academy",
      contactPerson: "Ritika Sharma",
      email: "ritika@eduspark.com",
      phone: "+91-9012345555",
      plan: {
        type: "Standard",
        chatLimit: 5000,
        expiryDate: "2025-08-20T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: false,
        customPrompt: "Assist students with online course queries.",
      },
      branding: {
        primaryColor: "#16a34a",
        secondaryColor: "#fbbf24",
      },
      analytics: { totalChats: 2023, activeUsers: 98, avgResponseTime: "3.2s" },
      status: "active",
    },
    {
      _id: "clt_004",
      companyName: "FitX Gym",
      contactPerson: "Rohit Yadav",
      email: "info@fitxgym.in",
      phone: "+91-9900112233",
      plan: {
        type: "Pro",
        chatLimit: 15000,
        expiryDate: "2026-01-05T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: true,
        customPrompt: "Act as a fitness trainer and guide.",
      },
      branding: {
        primaryColor: "#ef4444",
        secondaryColor: "#facc15",
      },
      analytics: {
        totalChats: 7432,
        activeUsers: 321,
        avgResponseTime: "2.7s",
      },
      status: "active",
    },
    {
      _id: "clt_005",
      companyName: "FinSmart Solutions",
      contactPerson: "Neha Gupta",
      email: "neha@finsmart.io",
      phone: "+91-9123456780",
      plan: {
        type: "Enterprise",
        chatLimit: 60000,
        expiryDate: "2026-06-10T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o",
        memoryEnabled: true,
        customPrompt: "Provide financial consulting support.",
      },
      branding: {
        primaryColor: "#0284c7",
        secondaryColor: "#22c55e",
      },
      analytics: {
        totalChats: 23410,
        activeUsers: 870,
        avgResponseTime: "1.8s",
      },
      status: "active",
    },
    {
      _id: "clt_006",
      companyName: "DreamHome Realty",
      contactPerson: "Arjun Mehta",
      email: "sales@dreamhome.com",
      phone: "+91-8877665544",
      plan: {
        type: "Standard",
        chatLimit: 7000,
        expiryDate: "2025-09-15T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: false,
        customPrompt: "Assist customers in finding real estate properties.",
      },
      branding: {
        primaryColor: "#f97316",
        secondaryColor: "#84cc16",
      },
      analytics: {
        totalChats: 3902,
        activeUsers: 154,
        avgResponseTime: "2.9s",
      },
      status: "active",
    },
    {
      _id: "clt_007",
      companyName: "MediLife Diagnostics",
      contactPerson: "Dr. Sameer Khan",
      email: "info@medilife.in",
      phone: "+91-9812334455",
      plan: {
        type: "Pro",
        chatLimit: 12000,
        expiryDate: "2026-02-01T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: true,
        customPrompt: "Answer medical test and health-related questions.",
      },
      branding: {
        primaryColor: "#06b6d4",
        secondaryColor: "#10b981",
      },
      analytics: {
        totalChats: 5321,
        activeUsers: 204,
        avgResponseTime: "2.1s",
      },
      status: "active",
    },
    {
      _id: "clt_008",
      companyName: "Eventura Pvt Ltd",
      contactPerson: "Sneha Kapoor",
      email: "support@eventura.com",
      phone: "+91-9812221122",
      plan: {
        type: "Standard",
        chatLimit: 8000,
        expiryDate: "2025-07-25T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: true,
        customPrompt: "Plan and manage event queries.",
      },
      branding: {
        primaryColor: "#ec4899",
        secondaryColor: "#a855f7",
      },
      analytics: {
        totalChats: 2812,
        activeUsers: 132,
        avgResponseTime: "3.0s",
      },
      status: "active",
    },
    {
      _id: "clt_009",
      companyName: "AutoCare Garage",
      contactPerson: "Ravi Tiwari",
      email: "help@autocare.in",
      phone: "+91-9000112233",
      plan: {
        type: "Pro",
        chatLimit: 12000,
        expiryDate: "2026-04-12T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o-mini",
        memoryEnabled: false,
        customPrompt: "Help customers with vehicle service and maintenance.",
      },
      branding: {
        primaryColor: "#f43f5e",
        secondaryColor: "#fde047",
      },
      analytics: {
        totalChats: 4532,
        activeUsers: 180,
        avgResponseTime: "2.5s",
      },
      status: "active",
    },
    {
      _id: "clt_010",
      companyName: "FoodNest Restaurants",
      contactPerson: "Tanya Verma",
      email: "contact@foodnest.in",
      phone: "+91-9550011122",
      plan: {
        type: "Enterprise",
        chatLimit: 70000,
        expiryDate: "2026-08-30T00:00:00Z",
      },
      aiSettings: {
        model: "gpt-4o",
        memoryEnabled: true,
        customPrompt: "Take food orders and assist customers.",
      },
      branding: {
        primaryColor: "#f59e0b",
        secondaryColor: "#ef4444",
      },
      analytics: {
        totalChats: 32450,
        activeUsers: 932,
        avgResponseTime: "1.7s",
      },
      status: "active",
    },
  ],
];
