export const users = [
  {
    _id: "usr_001",
    clientId: "clt_001",
    name: "Priya Sharma",
    email: "priya@kashitrip.com",
    role: "support-agent",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 231,
      avgResponseTime: "3.2s",
      lastActive: "2025-11-06T15:22:00Z",
    },
  },
  {
    _id: "usr_002",
    clientId: "clt_001",
    name: "Rahul Singh",
    email: "rahul@kashitrip.com",
    role: "admin",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 512,
      avgResponseTime: "2.8s",
      lastActive: "2025-11-05T11:40:00Z",
    },
  },
  {
    _id: "usr_003",
    clientId: "clt_002",
    name: "Aditi Rao",
    email: "aditi@technova.io",
    role: "support-engineer",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 940,
      avgResponseTime: "2.2s",
      lastActive: "2025-11-06T10:15:00Z",
    },
  },
  {
    _id: "usr_004",
    clientId: "clt_002",
    name: "Karan Patel",
    email: "karan@technova.io",
    role: "admin",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1301,
      avgResponseTime: "1.8s",
      lastActive: "2025-11-06T09:30:00Z",
    },
  },
  {
    _id: "usr_005",
    clientId: "clt_003",
    name: "Megha Joshi",
    email: "megha@eduspark.com",
    role: "teacher-assistant",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 140,
      avgResponseTime: "4.2s",
      lastActive: "2025-11-04T14:20:00Z",
    },
  },
  {
    _id: "usr_006",
    clientId: "clt_004",
    name: "Rohan Kapoor",
    email: "rohan@fitxgym.in",
    role: "trainer",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 832,
      avgResponseTime: "2.5s",
      lastActive: "2025-11-06T12:10:00Z",
    },
  },
  {
    _id: "usr_007",
    clientId: "clt_005",
    name: "Neha Verma",
    email: "neha@finsmart.io",
    role: "finance-advisor",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1021,
      avgResponseTime: "2.0s",
      lastActive: "2025-11-06T16:00:00Z",
    },
  },
  {
    _id: "usr_008",
    clientId: "clt_007",
    name: "Sahil Khan",
    email: "sahil@medilife.in",
    role: "doctor-assistant",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 642,
      avgResponseTime: "2.9s",
      lastActive: "2025-11-05T17:40:00Z",
    },
  },
  {
    _id: "usr_009",
    clientId: "clt_009",
    name: "Anjali Nair",
    email: "anjali@autocare.in",
    role: "support-agent",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 398,
      avgResponseTime: "3.0s",
      lastActive: "2025-11-06T14:10:00Z",
    },
  },
  {
    _id: "usr_010",
    clientId: "clt_010",
    name: "Tushar Mehta",
    email: "tushar@foodnest.in",
    role: "branch-manager",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 2150,
      avgResponseTime: "1.9s",
      lastActive: "2025-11-06T13:45:00Z",
    },
  },
  {
    _id: "usr_011",
    clientId: "clt_011",
    name: "Deepak Kumar",
    email: "deepak@techwise.in",
    role: "support-engineer",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 756,
      avgResponseTime: "2.4s",
      lastActive: "2025-11-06T11:30:00Z",
    },
  },
  {
    _id: "usr_012",
    clientId: "clt_012",
    name: "Ritu Gupta",
    email: "ritu@cloudserve.com",
    role: "admin",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1450,
      avgResponseTime: "2.1s",
      lastActive: "2025-11-06T15:20:00Z",
    },
  },
  {
    _id: "usr_013",
    clientId: "clt_013",
    name: "Amit Sharma",
    email: "amit@digitech.ai",
    role: "developer",
    status: "inactive",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 540,
      avgResponseTime: "3.8s",
      lastActive: "2025-10-30T18:45:00Z",
    },
  },
  {
    _id: "usr_014",
    clientId: "clt_011",
    name: "Sneha Verma",
    email: "sneha@techwise.in",
    role: "analyst",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 320,
      avgResponseTime: "2.9s",
      lastActive: "2025-11-06T09:15:00Z",
    },
  },
  {
    _id: "usr_015",
    clientId: "clt_014",
    name: "Rohan Mehta",
    email: "rohan@globex.com",
    role: "manager",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1289,
      avgResponseTime: "1.9s",
      lastActive: "2025-11-06T13:40:00Z",
    },
  },
  {
    _id: "usr_016",
    clientId: "clt_015",
    name: "Priya Nair",
    email: "priya@finconnect.io",
    role: "support",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 460,
      avgResponseTime: "3.2s",
      lastActive: "2025-11-06T14:05:00Z",
    },
  },
  {
    _id: "usr_017",
    clientId: "clt_016",
    name: "Arjun Singh",
    email: "arjun@nextdata.com",
    role: "developer",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 890,
      avgResponseTime: "2.7s",
      lastActive: "2025-11-06T16:50:00Z",
    },
  },
  {
    _id: "usr_018",
    clientId: "clt_012",
    name: "Neha Patil",
    email: "neha@cloudserve.com",
    role: "qa-tester",
    status: "inactive",
    permissions: {
      viewChats: false,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 210,
      avgResponseTime: "4.1s",
      lastActive: "2025-10-28T11:20:00Z",
    },
  },
  {
    _id: "usr_019",
    clientId: "clt_017",
    name: "Vikram Desai",
    email: "vikram@infosuite.ai",
    role: "admin",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1760,
      avgResponseTime: "1.8s",
      lastActive: "2025-11-06T17:10:00Z",
    },
  },
  {
    _id: "usr_020",
    clientId: "clt_015",
    name: "Manisha Roy",
    email: "manisha@finconnect.io",
    role: "support",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 608,
      avgResponseTime: "3.0s",
      lastActive: "2025-11-06T15:50:00Z",
    },
  },
  {
    _id: "usr_021",
    clientId: "clt_013",
    name: "Kabir Bansal",
    email: "kabir@digitech.ai",
    role: "developer",
    status: "inactive",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 485,
      avgResponseTime: "3.5s",
      lastActive: "2025-10-29T09:50:00Z",
    },
  },
  {
    _id: "usr_022",
    clientId: "clt_018",
    name: "Ananya Sen",
    email: "ananya@mindmesh.io",
    role: "analyst",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 368,
      avgResponseTime: "2.8s",
      lastActive: "2025-11-06T14:30:00Z",
    },
  },
  {
    _id: "usr_023",
    clientId: "clt_019",
    name: "Rahul Tiwari",
    email: "rahul@codesmiths.io",
    role: "lead-engineer",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1345,
      avgResponseTime: "2.3s",
      lastActive: "2025-11-06T16:00:00Z",
    },
  },
  {
    _id: "usr_024",
    clientId: "clt_018",
    name: "Meena Joshi",
    email: "meena@mindmesh.io",
    role: "support",
    status: "inactive",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 278,
      avgResponseTime: "3.9s",
      lastActive: "2025-10-31T19:00:00Z",
    },
  },
  {
    _id: "usr_025",
    clientId: "clt_017",
    name: "Rakesh Sinha",
    email: "rakesh@infosuite.ai",
    role: "data-analyst",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 512,
      avgResponseTime: "2.5s",
      lastActive: "2025-11-06T12:50:00Z",
    },
  },
  {
    _id: "usr_026",
    clientId: "clt_020",
    name: "Sonia Kapoor",
    email: "sonia@alphachat.in",
    role: "qa-tester",
    status: "inactive",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 189,
      avgResponseTime: "4.6s",
      lastActive: "2025-10-25T17:10:00Z",
    },
  },
  {
    _id: "usr_027",
    clientId: "clt_014",
    name: "Tarun Ghosh",
    email: "tarun@globex.com",
    role: "admin",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: true,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 1620,
      avgResponseTime: "1.7s",
      lastActive: "2025-11-06T18:10:00Z",
    },
  },
  {
    _id: "usr_028",
    clientId: "clt_019",
    name: "Krishna Patel",
    email: "krishna@codesmiths.io",
    role: "intern",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: false,
    },
    usage: {
      totalChats: 112,
      avgResponseTime: "3.6s",
      lastActive: "2025-11-06T09:20:00Z",
    },
  },
  {
    _id: "usr_029",
    clientId: "clt_020",
    name: "Divya Chauhan",
    email: "divya@alphachat.in",
    role: "developer",
    status: "active",
    permissions: {
      viewChats: true,
      editFlows: true,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 680,
      avgResponseTime: "2.9s",
      lastActive: "2025-11-06T13:10:00Z",
    },
  },
  {
    _id: "usr_030",
    clientId: "clt_016",
    name: "Harsh Malhotra",
    email: "harsh@nextdata.com",
    role: "support-engineer",
    status: "inactive",
    permissions: {
      viewChats: true,
      editFlows: false,
      manageUsers: false,
      viewAnalytics: true,
    },
    usage: {
      totalChats: 305,
      avgResponseTime: "3.7s",
      lastActive: "2025-11-01T20:15:00Z",
    },
  },
];
