  export const clients = [
    {
      id:1,
      name: "InnovateX Corp",
      plan: "Pro Plan",
      aiStatus: "Active",
      performance: { chats: 1400, conversion: 78, engagement: 92 },
    },
    {
      id:2,
      name: "TechNova",
      plan: "Enterprise Plan",
      aiStatus: "Inactive",
      performance: { chats: 300, conversion: 50, engagement: 65 },
    },
    {
      id:3,
      name: "NextGen Systems",
      plan: "Growth Plan",
      aiStatus: "Active",
      performance: { chats: 900, conversion: 68, engagement: 85 },
    },
    {
      id:4,
      name: "TechNova",
      plan: "Enterprise Plan",
      aiStatus: "Inactive",
      performance: { chats: 300, conversion: 50, engagement: 65 },
    },
    {
      id:5,
      name: "NextGen Systems",
      plan: "Growth Plan",
      aiStatus: "Active",
      performance: { chats: 900, conversion: 68, engagement: 85 },
    },
    {
      id:6,
      name: "TechNova",
      plan: "Enterprise Plan",
      aiStatus: "Inactive",
      performance: { chats: 300, conversion: 50, engagement: 65 },
    },
    {
      id:7,
      name: "NextGen Systems",
      plan: "Growth Plan",
      aiStatus: "Active",
      performance: { chats: 900, conversion: 68, engagement: 85 },
    },
  ];